import React from 'react';
import Skeleton from 'react-loading-skeleton';

export default function AddAndEditindCourseAndLesson() {
  return (
    <div className="flex flex-col gap-7 py-5">
      <div className="grid grid-cols-3 gap-5">
        <div>
          <Skeleton
            height={10}
            count={1}
            width={150}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
          <Skeleton
            height={40}
            count={1}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
        </div>
        <div>
          <Skeleton
            height={10}
            count={1}
            width={150}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
          <Skeleton
            height={40}
            count={1}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
        </div>
        <div>
          <Skeleton
            height={10}
            count={1}
            width={150}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
          <Skeleton
            height={40}
            count={1}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
        </div>
      </div>
      <div className="grid grid-cols-2 gap-5">
        <div>
          <Skeleton
            height={10}
            count={1}
            width={150}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
          <Skeleton
            height={40}
            count={1}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
        </div>
        <div>
          <Skeleton
            height={10}
            count={1}
            width={150}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
          <Skeleton
            height={40}
            count={1}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
        </div>
      </div>
      <div className="grid grid-cols-3 gap-5">
        <div>
          <Skeleton
            height={10}
            count={1}
            width={150}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
          <Skeleton
            height={130}
            count={1}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
        </div>
        <div>
          <Skeleton
            height={10}
            count={1}
            width={150}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
          <Skeleton
            height={130}
            count={1}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
        </div>
        <div>
          <Skeleton
            height={10}
            count={1}
            width={150}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
          <Skeleton
            height={130}
            count={1}
            baseColor="#e5e7eb"
            highlightColor="#fff"
          />
        </div>
      </div>
    </div>
  );
}
