import type { Metadata } from 'next';
import { Cairo } from 'next/font/google';
import './globals.css';
import Nav from './_components/Navbar/Nav';

const cairoFont = Cairo({
  variable: '--font-cairo',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Daleel',
  icons: {
    icon: '/logo.png',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${cairoFont.variable} max-w-[1200px] px-5 lg:px-0 mx-auto overflow-x-hidden`}
      >
        <main>
          <nav>
            <Nav />
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
