import type { Metadata } from 'next';
import { Cairo } from 'next/font/google';
import './globals.css';
import Nav from './_components/Navbar/Nav';
import ReactQueryProvider from './_components/ReactQueryProvider/ReactQueryProvider';
import { Toaster } from 'react-hot-toast';
import 'react-loading-skeleton/dist/skeleton.css';
const cairoFont = Cairo({
  subsets: ['arabic'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Daleel',
  icons: {
    icon: '/logo.png',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${cairoFont.className} max-w-[1200px] px-2 mx-auto overflow-x-hidden `}
      >
        <ReactQueryProvider>
          <main>
            <nav>
              <Nav />
            </nav>
            {children}
          </main>
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
